export const wordTicketMovieList = [{
	"title": "阿凡达 Avatar",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2180085848.jpg",
	"score": "8.6",
	"scoreNum": "647411人评价",
	"director": " 詹姆斯·卡梅隆",
	"actors": "萨姆·沃辛顿 / 佐伊·索尔达娜 / 西格妮·韦弗",
	"type": "动作 / 战争 / 科幻 / 冒险",
	"country": "美国/英国",
	"date": "2009",
	"ticket": "$2,788.0 百万"
}, {
	"title": "泰坦尼克号 Titanic",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457760035.jpg",
	"score": "9.3",
	"scoreNum": "902391人评价",
	"director": " 詹姆斯·卡梅隆",
	"actors": "莱昂纳多·迪卡普里奥 / 凯特·温丝莱特 / 比利·赞恩",
	"type": "剧情 / 爱情 / 灾难",
	"country": "美国",
	"date": "1997",
	"ticket": "$2,187.5 百万"
}, {
	"title": "星球大战7：原力觉醒 Star Wars: The Force Awakens",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2293954118.jpg",
	"score": "7.1",
	"scoreNum": "155294人评价",
	"director": " J·J·艾布拉姆斯",
	"actors": "黛西·雷德利 / 约翰·博耶加 / 哈里森·福特",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2015",
	"ticket": "$2,068.2 百万"
}, {
	"title": "复仇者联盟3：无限战争 Avengers: Infinity War",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2517753454.jpg",
	"score": "8.1",
	"scoreNum": "438280人评价",
	"director": " 安东尼·罗素 / 乔·罗素",
	"actors": "小罗伯特·唐尼 / 克里斯·海姆斯沃斯 / 克里斯·埃文斯",
	"type": "动作 / 科幻 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2018",
	"ticket": "$2,046.5 百万"
}, {
	"title": "侏罗纪世界 Jurassic World",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2246217861.jpg",
	"score": "7.7",
	"scoreNum": "255197人评价",
	"director": " 科林·特雷沃罗",
	"actors": "克里斯·帕拉特 / 布莱丝·达拉斯·霍华德 / 文森特·多诺费奥",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国/中国大陆",
	"date": "2015",
	"ticket": "$1,671.7 百万"
}, {
	"title": "复仇者联盟 The Avengers",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1524904031.jpg",
	"score": "8.1",
	"scoreNum": "397460人评价",
	"director": " 乔斯·韦登",
	"actors": "小罗伯特·唐尼 / 克里斯·埃文斯 / 斯嘉丽·约翰逊",
	"type": "动作 / 科幻 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2012",
	"ticket": "$1,518.8 百万"
}, {
	"title": "速度与激情7 Furious 7",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2233706697.jpg",
	"score": "8.3",
	"scoreNum": "297977人评价",
	"director": " 温子仁",
	"actors": "范·迪塞尔 / 保罗·沃克 / 杰森·斯坦森",
	"type": "动作 / 犯罪 / 惊悚",
	"country": "美国/中国大陆/日本",
	"date": "2015",
	"ticket": "$1,516.0 百万"
}, {
	"title": "复仇者联盟2：奥创纪元 Avengers: Age of Ultron",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2237747953.jpg",
	"score": "7.3",
	"scoreNum": "284428人评价",
	"director": " 乔斯·韦登",
	"actors": "小罗伯特·唐尼 / 克里斯·海姆斯沃斯 / 马克·鲁弗洛",
	"type": "动作 / 科幻 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2015",
	"ticket": "$1,405.4 百万"
}, {
	"title": "黑豹 Black Panther",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2512123434.jpg",
	"score": "6.4",
	"scoreNum": "239961人评价",
	"director": " 瑞恩·库格勒",
	"actors": "查德维克·博斯曼 / 露皮塔·尼永奥 / 迈克尔·B·乔丹",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2018",
	"ticket": "$1,346.8 百万"
}, {
	"title": "哈利·波特与死亡圣器(下) Harry Potter and the Deathly Hallows: Part 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p917846733.jpg",
	"score": "8.7",
	"scoreNum": "338571人评价",
	"director": " 大卫·叶茨",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "剧情 / 悬疑 / 奇幻 / 冒险",
	"country": "美国/英国",
	"date": "2011",
	"ticket": "$1,341.5 百万"
}, {
	"title": "星球大战8：最后的绝地武士 Star Wars: The Last Jedi",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2506694509.jpg",
	"score": "7.1",
	"scoreNum": "97775人评价",
	"director": " 莱恩·约翰逊",
	"actors": "马克·哈米尔 / 凯丽·费雪 / 黛西·雷德利",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$1,332.5 百万"
}, {
	"title": "侏罗纪世界2 Jurassic World: Fallen Kingdom",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2522069454.jpg",
	"score": "6.7",
	"scoreNum": "225060人评价",
	"director": " 胡安·安东尼奥·巴亚纳",
	"actors": "克里斯·帕拉特 / 布莱丝·达拉斯·霍华德 / 贾斯蒂斯·史密斯",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国/西班牙",
	"date": "2018",
	"ticket": "$1,304.8 百万"
}, {
	"title": "冰雪奇缘 Frozen",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2166640945.jpg",
	"score": "8.3",
	"scoreNum": "353944人评价",
	"director": " 克里斯·巴克 / 珍妮弗·李",
	"actors": "克里斯汀·贝尔 / 伊迪娜·门泽尔 / 乔纳森·格罗夫",
	"type": "喜剧 / 动画 / 奇幻 / 歌舞",
	"country": "美国",
	"date": "2013",
	"ticket": "$1,276.5 百万"
}, {
	"title": "美女与野兽 Beauty and the Beast",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2417948644.jpg",
	"score": "7.1",
	"scoreNum": "208062人评价",
	"director": " 比尔·康顿",
	"actors": "艾玛·沃森 / 丹·史蒂文斯 / 卢克·伊万斯",
	"type": "爱情 / 奇幻 / 歌舞",
	"country": "美国",
	"date": "2017",
	"ticket": "$1,263.5 百万"
}, {
	"title": "超人总动员2 Incredibles 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2522880251.jpg",
	"score": "8.0",
	"scoreNum": "122200人评价",
	"director": " 布拉德·伯德",
	"actors": "格雷格·T·尼尔森 / 霍利·亨特 / 莎拉·沃威尔",
	"type": "喜剧 / 动作 / 动画 / 冒险",
	"country": "美国",
	"date": "2018",
	"ticket": "$1,238.6 百万"
}, {
	"title": "速度与激情8 The Fate of the Furious",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2444256500.jpg",
	"score": "7.0",
	"scoreNum": "227224人评价",
	"director": " F·加里·格雷",
	"actors": "范·迪塞尔 / 道恩·强森 / 查理兹·塞隆",
	"type": "动作 / 犯罪",
	"country": "美国",
	"date": "2017",
	"ticket": "$1,236.0 百万"
}, {
	"title": "钢铁侠3 Iron Man 3",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1955027201.jpg",
	"score": "7.7",
	"scoreNum": "263528人评价",
	"director": " 沙恩·布莱克",
	"actors": "小罗伯特·唐尼 / 盖·皮尔斯 / 格温妮斯·帕特洛",
	"type": "动作 / 科幻",
	"country": "美国/中国大陆",
	"date": "2013",
	"ticket": "$1,214.8 百万"
}, {
	"title": "小黄人大眼萌 Minions",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2265761240.jpg",
	"score": "7.4",
	"scoreNum": "156549人评价",
	"director": " 凯尔·巴尔达 / 皮埃尔·柯芬",
	"actors": "桑德拉·布洛克 / 乔恩·哈姆 / 迈克尔·基顿",
	"type": "喜剧 / 动画",
	"country": "美国",
	"date": "2015",
	"ticket": "$1,159.4 百万"
}, {
	"title": "美国队长3 Captain America: Civil War",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2332503406.jpg",
	"score": "7.7",
	"scoreNum": "283613人评价",
	"director": " 安东尼·罗素 / 乔·罗素",
	"actors": "克里斯·埃文斯 / 小罗伯特·唐尼 / 斯嘉丽·约翰逊",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2016",
	"ticket": "$1,153.3 百万"
}, {
	"title": "变形金刚3 Transformers: Dark of the Moon",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1056093671.jpg",
	"score": "7.1",
	"scoreNum": "235327人评价",
	"director": " 迈克尔·贝",
	"actors": "希亚·拉博夫 / 罗茜·汉丁顿-惠特莉 / 乔什·杜哈明",
	"type": "动作 / 科幻",
	"country": "美国",
	"date": "2011",
	"ticket": "$1,123.8 百万"
}, {
	"title": "指环王3：王者无敌 The Lord of the Rings: The Return of the King",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910825503.jpg",
	"score": "9.1",
	"scoreNum": "361396人评价",
	"director": " 彼得·杰克逊",
	"actors": "维果·莫腾森 / 伊莱贾·伍德 / 西恩·奥斯汀",
	"type": "剧情 / 动作 / 奇幻 / 冒险",
	"country": "美国/新西兰",
	"date": "2003",
	"ticket": "$1,119.9 百万"
}, {
	"title": "007：大破天幕杀机 Skyfall",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1706050033.jpg",
	"score": "7.0",
	"scoreNum": "180839人评价",
	"director": " 萨姆·门德斯",
	"actors": "丹尼尔·克雷格 / 朱迪·丹奇 / 哈维尔·巴登",
	"type": "动作 / 惊悚 / 犯罪 / 冒险",
	"country": "英国/美国",
	"date": "2012",
	"ticket": "$1,108.6 百万"
}, {
	"title": "变形金刚4：绝迹重生 Transformers: Age of Extinction",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2187231762.jpg",
	"score": "6.5",
	"scoreNum": "217819人评价",
	"director": " 迈克尔·贝",
	"actors": "马克·沃尔伯格 / 斯坦利·图齐 / 凯尔希·格兰莫",
	"type": "动作 / 科幻",
	"country": "美国/中国大陆",
	"date": "2014",
	"ticket": "$1,104.1 百万"
}, {
	"title": "蝙蝠侠：黑暗骑士崛起 The Dark Knight Rises",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1706428744.jpg",
	"score": "8.6",
	"scoreNum": "350640人评价",
	"director": " 克里斯托弗·诺兰",
	"actors": "克里斯蒂安·贝尔 / 汤姆·哈迪 / 安妮·海瑟薇",
	"type": "剧情 / 动作 / 科幻 / 犯罪 / 惊悚",
	"country": "美国/英国",
	"date": "2012",
	"ticket": "$1,084.9 百万"
}, {
	"title": "玩具总动员3 Toy Story 3",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1283675359.jpg",
	"score": "8.8",
	"scoreNum": "228225人评价",
	"director": " 李·昂克里奇",
	"actors": "汤姆·汉克斯 / 蒂姆·艾伦 / 琼·库萨克",
	"type": "喜剧 / 动画 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2010",
	"ticket": "$1,067.0 百万"
}, {
	"title": "加勒比海盗2：聚魂棺 Pirates of the Caribbean: Dead Man's Chest",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1076822803.jpg",
	"score": "8.2",
	"scoreNum": "234658人评价",
	"director": " 戈尔·维宾斯基",
	"actors": "约翰尼·德普 / 奥兰多·布鲁姆 / 凯拉·奈特莉",
	"type": "动作 / 冒险 / 奇幻",
	"country": "美国",
	"date": "2006",
	"ticket": "$1,066.2 百万"
}, {
	"title": "星球大战外传：侠盗一号 Rogue One: A Star Wars Story",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2403049086.jpg",
	"score": "7.3",
	"scoreNum": "126286人评价",
	"director": " 加里斯·爱德华斯",
	"actors": "菲丽希缇·琼斯 / 迭戈·卢纳 / 甄子丹",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2016",
	"ticket": "$1,056.1 百万"
}, {
	"title": "加勒比海盗4：惊涛怪浪 Pirates of the Caribbean: On Stranger Tides",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p995422651.jpg",
	"score": "7.5",
	"scoreNum": "232216人评价",
	"director": " 罗伯·马歇尔",
	"actors": "约翰尼·德普 / 佩内洛普·克鲁兹 / 杰弗里·拉什",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2011",
	"ticket": "$1,045.7 百万"
}, {
	"title": "神偷奶爸3 Despicable Me 3",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2469070974.jpg",
	"score": "6.8",
	"scoreNum": "153179人评价",
	"director": " 凯尔·巴尔达 / 皮埃尔·柯芬 / 埃里克·吉隆",
	"actors": "史蒂夫·卡瑞尔 / 克里斯汀·韦格 / 崔·帕克",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$1,034.8 百万"
}, {
	"title": "侏罗纪公园 Jurassic Park",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2076443176.jpg",
	"score": "8.0",
	"scoreNum": "186725人评价",
	"director": " 史蒂文·斯皮尔伯格",
	"actors": "山姆·尼尔 / 劳拉·邓恩 / 杰夫·高布伦",
	"type": "科幻 / 惊悚 / 冒险",
	"country": "美国",
	"date": "1993",
	"ticket": "$1,029.2 百万"
}, {
	"title": "海底总动员2：多莉去哪儿 Finding Dory",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2356015154.jpg",
	"score": "7.4",
	"scoreNum": "64485人评价",
	"director": " 安德鲁·斯坦顿 / 安格斯·麦克莱恩",
	"actors": "艾伦·德杰尼勒斯 / 艾伯特·布鲁克斯 / 艾德·奥尼尔",
	"type": "喜剧 / 动画 / 冒险 / 家庭",
	"country": "美国",
	"date": "2016",
	"ticket": "$1,028.6 百万"
}, {
	"title": "星球大战前传1：幽灵的威胁 Star Wars: Episode I - The Phantom Menace",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2308392633.jpg",
	"score": "8.1",
	"scoreNum": "71386人评价",
	"director": " 乔治·卢卡斯",
	"actors": "连姆·尼森 / 伊万·麦克格雷格 / 娜塔莉·波特曼",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "1999",
	"ticket": "$1,027.0 百万"
}, {
	"title": "爱丽丝梦游仙境 Alice in Wonderland",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p481556187.jpg",
	"score": "7.1",
	"scoreNum": "244901人评价",
	"director": " 蒂姆·波顿",
	"actors": "米娅·华希科沃斯卡 / 约翰尼·德普 / 海伦娜·伯翰·卡特",
	"type": "奇幻 / 冒险",
	"country": "美国",
	"date": "2010",
	"ticket": "$1,025.5 百万"
}, {
	"title": "疯狂动物城 Zootopia",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2315672647.jpg",
	"score": "9.2",
	"scoreNum": "730961人评价",
	"director": " 拜伦·霍华德 / 瑞奇·摩尔 / 杰拉德·布什",
	"actors": "金妮弗·古德温 / 杰森·贝特曼 / 伊德里斯·艾尔巴",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2016",
	"ticket": "$1,023.8 百万"
}, {
	"title": "霍比特人1：意外之旅 The Hobbit: An Unexpected Journey",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1716297390.jpg",
	"score": "8.2",
	"scoreNum": "254420人评价",
	"director": " 彼得·杰克逊",
	"actors": "伊恩·麦克莱恩 / 马丁·弗瑞曼 / 理查德·阿米蒂奇",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国/新西兰",
	"date": "2012",
	"ticket": "$1,021.1 百万"
}, {
	"title": "蝙蝠侠：黑暗骑士 The Dark Knight",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p462657443.jpg",
	"score": "9.1",
	"scoreNum": "441353人评价",
	"director": " 克里斯托弗·诺兰",
	"actors": "克里斯蒂安·贝尔 / 希斯·莱杰 / 艾伦·艾克哈特",
	"type": "剧情 / 动作 / 科幻 / 犯罪 / 惊悚",
	"country": "美国/英国",
	"date": "2008",
	"ticket": "$1,004.6 百万"
}, {
	"title": "哈利·波特与魔法石 Harry Potter and the Sorcerer's Stone",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p804947166.jpg",
	"score": "8.8",
	"scoreNum": "358875人评价",
	"director": " 克里斯·哥伦布",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "奇幻 / 冒险",
	"country": "美国/英国",
	"date": "2001",
	"ticket": "$974.8 百万"
}, {
	"title": "神偷奶爸2 Despicable Me 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2164225595.jpg",
	"score": "8.0",
	"scoreNum": "266641人评价",
	"director": " 皮埃尔·柯芬 / 克里斯·雷纳德",
	"actors": "史蒂夫·卡瑞尔 / 克里斯汀·韦格 / 本杰明·布拉特",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2013",
	"ticket": "$970.8 百万"
}, {
	"title": "狮子王 The Lion King",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p726659067.jpg",
	"score": "8.9",
	"scoreNum": "357860人评价",
	"director": " 罗杰·阿勒斯 / 罗伯·明可夫",
	"actors": "乔纳森·泰勒·托马斯 / 马修·布罗德里克 / 杰瑞米·艾恩斯",
	"type": "剧情 / 动画 / 冒险 / 歌舞 / 家庭",
	"country": "美国",
	"date": "1994",
	"ticket": "$968.5 百万"
}, {
	"title": "奇幻森林 The Jungle Book",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2326337223.jpg",
	"score": "7.8",
	"scoreNum": "176295人评价",
	"director": " 乔恩·费儒",
	"actors": "尼尔·塞西 / 比尔·默瑞 / 本·金斯利",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2016",
	"ticket": "$966.6 百万"
}, {
	"title": "加勒比海盗3：世界的尽头 Pirates of the Caribbean: At World's End",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1076818175.jpg",
	"score": "8.1",
	"scoreNum": "218722人评价",
	"director": " 戈尔·维宾斯基",
	"actors": "约翰尼·德普 / 杰弗里·拉什 / 奥兰多·布鲁姆",
	"type": "动作 / 冒险 / 奇幻",
	"country": "美国",
	"date": "2007",
	"ticket": "$963.4 百万"
}, {
	"title": "勇敢者游戏：决战丛林 Jumanji: Welcome to the Jungle",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2506258944.jpg",
	"score": "6.9",
	"scoreNum": "119835人评价",
	"director": " 杰克·卡斯丹",
	"actors": "道恩·强森 / 凯文·哈特 / 杰克·布莱克",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$962.1 百万"
}, {
	"title": "哈利·波特与死亡圣器(上) Harry Potter and the Deathly Hallows: Part 1",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p721429854.jpg",
	"score": "8.0",
	"scoreNum": "217358人评价",
	"director": " 大卫·叶茨",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2010",
	"ticket": "$960.3 百万"
}, {
	"title": "霍比特人2：史矛革之战 The Hobbit: The Desolation of Smaug",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2166784595.jpg",
	"score": "8.2",
	"scoreNum": "221263人评价",
	"director": " 彼得·杰克逊",
	"actors": "伊恩·麦克莱恩 / 马丁·弗瑞曼 / 理查德·阿米蒂奇",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国/新西兰",
	"date": "2013",
	"ticket": "$958.4 百万"
}, {
	"title": "霍比特人3：五军之战 The Hobbit: The Battle of the Five Armies",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2219406504.jpg",
	"score": "8.3",
	"scoreNum": "222122人评价",
	"director": " 彼得·杰克逊",
	"actors": "马丁·弗瑞曼 / 伊恩·麦克莱恩 / 理查德·阿米蒂奇",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国/新西兰",
	"date": "2014",
	"ticket": "$956.0 百万"
}, {
	"title": "海底总动员 Finding Nemo",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1755893801.jpg",
	"score": "8.3",
	"scoreNum": "230097人评价",
	"director": " 安德鲁·斯坦顿 / 李·昂克里奇",
	"actors": "艾伯特·布鲁克斯 / 艾伦·德杰尼勒斯 / 亚历山大·古尔德",
	"type": "动画 / 冒险 / 喜剧 / 家庭",
	"country": "美国/澳大利亚",
	"date": "2003",
	"ticket": "$940.3 百万"
}, {
	"title": "哈利·波特与凤凰社 Harry Potter and the Order of the Phoenix",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p443403700.jpg",
	"score": "7.9",
	"scoreNum": "195751人评价",
	"director": " 大卫·叶茨",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2007",
	"ticket": "$939.9 百万"
}, {
	"title": "哈利·波特与混血王子 Harry Potter and the Half-Blood Prince",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1108070214.jpg",
	"score": "7.6",
	"scoreNum": "197499人评价",
	"director": " 大卫·叶茨",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2009",
	"ticket": "$934.4 百万"
}, {
	"title": "指环王2：双塔奇兵 The Lord of the Rings: The Two Towers",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p909265336.jpg",
	"score": "9.0",
	"scoreNum": "338937人评价",
	"director": " 彼得·杰克逊",
	"actors": "伊莱贾·伍德 / 西恩·奥斯汀 / 伊恩·麦克莱恩",
	"type": "剧情 / 动作 / 奇幻 / 冒险",
	"country": "美国/新西兰",
	"date": "2002",
	"ticket": "$926.0 百万"
}, {
	"title": "怪物史瑞克2 Shrek 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910896984.jpg",
	"score": "7.5",
	"scoreNum": "73394人评价",
	"director": " 安德鲁·亚当森 / 凯利·阿斯博瑞 / 康拉德·弗农",
	"actors": "麦克·梅尔斯 / 艾迪·墨菲 / 卡梅隆·迪亚兹",
	"type": "动画 / 冒险 / 喜剧 / 家庭 / 奇幻",
	"country": "美国",
	"date": "2004",
	"ticket": "$919.8 百万"
}, {
	"title": "哈利·波特与火焰杯 Harry Potter and the Goblet of Fire",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p735391084.jpg",
	"score": "8.2",
	"scoreNum": "207458人评价",
	"director": " 迈克·内威尔",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2005",
	"ticket": "$896.9 百万"
}, {
	"title": "蜘蛛侠3 Spider-Man 3",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1344981868.jpg",
	"score": "7.1",
	"scoreNum": "125267人评价",
	"director": " 山姆·雷米",
	"actors": "托比·马奎尔 / 克斯汀·邓斯特 / 詹姆斯·弗兰科",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2007",
	"ticket": "$890.9 百万"
}, {
	"title": "冰川时代3 Ice Age: Dawn of the Dinosaurs",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2213132432.jpg",
	"score": "8.2",
	"scoreNum": "162985人评价",
	"director": " 卡洛斯·沙尔丹哈 / 麦克·特米尔",
	"actors": "雷·罗马诺 / 约翰·雷吉扎莫 / 丹尼斯·利瑞",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2009",
	"ticket": "$886.7 百万"
}, {
	"title": "007：幽灵党 Spectre",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2276234635.jpg",
	"score": "6.2",
	"scoreNum": "125616人评价",
	"director": " 萨姆·门德斯",
	"actors": "丹尼尔·克雷格 / 克里斯托弗·沃尔兹 / 蕾雅·赛杜",
	"type": "动作 / 惊悚 / 冒险",
	"country": "英国/美国",
	"date": "2015",
	"ticket": "$880.7 百万"
}, {
	"title": "蜘蛛侠：英雄归来 Spider-Man: Homecoming",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2497756471.jpg",
	"score": "7.3",
	"scoreNum": "242703人评价",
	"director": " 乔·沃茨",
	"actors": "汤姆·赫兰德 / 小罗伯特·唐尼 / 玛丽莎·托梅",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$880.2 百万"
}, {
	"title": "哈利·波特与密室 Harry Potter and the Chamber of Secrets",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1082651990.jpg",
	"score": "8.3",
	"scoreNum": "229805人评价",
	"director": " 克里斯·哥伦布",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "奇幻 / 冒险",
	"country": "美国/英国/德国",
	"date": "2002",
	"ticket": "$879.0 百万"
}, {
	"title": "冰川时代4 Ice Age: Continental Drift",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1596241117.jpg",
	"score": "8.0",
	"scoreNum": "159932人评价",
	"director": " 麦克·特米尔 / 史蒂夫·马蒂诺",
	"actors": "阿兹·安萨里 / 乔·贝哈 / 克里斯托弗·坎贝尔",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2012",
	"ticket": "$877.2 百万"
}, {
	"title": "爱宠大机密 The Secret Life of Pets",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2363369616.jpg",
	"score": "7.5",
	"scoreNum": "147765人评价",
	"director": " 克里斯·雷纳德 / 亚罗·切尼",
	"actors": "路易·C·K / 艾瑞克·斯通斯崔特 / 凯文·哈特",
	"type": "喜剧 / 动画",
	"country": "美国",
	"date": "2016",
	"ticket": "$875.5 百万"
}, {
	"title": "蝙蝠侠大战超人：正义黎明 Batman v Superman: Dawn of Justice",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2316834186.jpg",
	"score": "6.7",
	"scoreNum": "171480人评价",
	"director": " 扎克·施奈德",
	"actors": "本·阿弗莱克 / 亨利·卡维尔 / 艾米·亚当斯",
	"type": "动作 / 科幻 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2016",
	"ticket": "$873.6 百万"
}, {
	"title": "指环王1：魔戒再现 The Lord of the Rings: The Fellowship of the Ring",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1354436051.jpg",
	"score": "8.9",
	"scoreNum": "379477人评价",
	"director": " 彼得·杰克逊",
	"actors": "伊莱贾·伍德 / 西恩·奥斯汀 / 伊恩·麦克莱恩",
	"type": "剧情 / 动作 / 奇幻 / 冒险",
	"country": "新西兰/美国",
	"date": "2001",
	"ticket": "$871.5 百万"
}, {
	"title": "战狼2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2494701965.jpg",
	"score": "7.1",
	"scoreNum": "576785人评价",
	"director": " 吴京",
	"actors": "吴京 / 弗兰克·格里罗 / 吴刚",
	"type": "动作",
	"country": "中国大陆",
	"date": "2017",
	"ticket": "$870.3 百万"
}, {
	"title": "饥饿游戏2：星火燎原 The Hunger Games: Catching Fire",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2156684911.jpg",
	"score": "7.3",
	"scoreNum": "161762人评价",
	"director": " 弗朗西斯·劳伦斯",
	"actors": "詹妮弗·劳伦斯 / 乔什·哈切森 / 利亚姆·海姆斯沃斯",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2013",
	"ticket": "$865.0 百万"
}, {
	"title": "银河护卫队2 Guardians of the Galaxy Vol. 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2455261804.jpg",
	"score": "8.0",
	"scoreNum": "276001人评价",
	"director": " 詹姆斯·古恩",
	"actors": "克里斯·帕拉特 / 佐伊·索尔达娜 / 戴夫·巴蒂斯塔",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$863.8 百万"
}, {
	"title": "头脑特工队 Inside Out",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.jpg",
	"score": "8.7",
	"scoreNum": "282229人评价",
	"director": " 彼特·道格特 / 罗纳尔多·德尔·卡门",
	"actors": "艾米·波勒 / 菲利丝·史密斯 / 理查德·坎德",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2015",
	"ticket": "$857.6 百万"
}, {
	"title": "雷神3：诸神黄昏 Thor: Ragnarok",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2500451074.jpg",
	"score": "7.4",
	"scoreNum": "236707人评价",
	"director": " 塔伊加·维迪提",
	"actors": "克里斯·海姆斯沃斯 / 汤姆·希德勒斯顿 / 凯特·布兰切特",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$854.0 百万"
}, {
	"title": "星球大战前传3：西斯的复仇 Star Wars: Episode III - Revenge of the Sith",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p533908031.jpg",
	"score": "8.3",
	"scoreNum": "63196人评价",
	"director": " 乔治·卢卡斯",
	"actors": "伊万·麦克格雷格 / 娜塔莉·波特曼 / 海登·克里斯滕森",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2005",
	"ticket": "$848.8 百万"
}, {
	"title": "变形金刚2 Transformers: Revenge of the Fallen",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1076838705.jpg",
	"score": "7.6",
	"scoreNum": "249405人评价",
	"director": " 迈克尔·贝",
	"actors": "希亚·拉博夫 / 梅根·福克斯 / 乔什·杜哈明",
	"type": "动作 / 科幻",
	"country": "美国",
	"date": "2009",
	"ticket": "$836.3 百万"
}, {
	"title": "暮光之城4：破晓(下) The Twilight Saga: Breaking Dawn - Part 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1725916674.jpg",
	"score": "6.6",
	"scoreNum": "75662人评价",
	"director": " 比尔·康顿",
	"actors": "罗伯特·帕丁森 / 克里斯汀·斯图尔特 / 泰勒·洛特纳",
	"type": "剧情 / 爱情 / 惊悚 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2012",
	"ticket": "$829.7 百万"
}, {
	"title": "盗梦空间 Inception",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p513344864.jpg",
	"score": "9.3",
	"scoreNum": "981588人评价",
	"director": " 克里斯托弗·诺兰",
	"actors": "莱昂纳多·迪卡普里奥 / 约瑟夫·高登-莱维特 / 艾伦·佩吉",
	"type": "剧情 / 科幻 / 悬疑 / 冒险",
	"country": "美国/英国",
	"date": "2010",
	"ticket": "$828.3 百万"
}, {
	"title": "毒液：致命守护者 Venom",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2537158013.jpg",
	"score": "7.3",
	"scoreNum": "315824人评价",
	"director": " 鲁本·弗雷斯彻",
	"actors": "汤姆·哈迪 / 米歇尔·威廉姆斯 / 里兹·阿迈德",
	"type": "动作 / 科幻 / 惊悚",
	"country": "美国/中国大陆",
	"date": "2018",
	"ticket": "$822.5 百万"
}, {
	"title": "神奇女侠 Wonder Woman",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2460006593.jpg",
	"score": "7.1",
	"scoreNum": "279113人评价",
	"director": " 派蒂·杰金斯",
	"actors": "盖尔·加朵 / 克里斯·派恩 / 康妮·尼尔森",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$821.8 百万"
}, {
	"title": "蜘蛛侠 Spider-Man",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457050361.jpg",
	"score": "7.6",
	"scoreNum": "195974人评价",
	"director": " 山姆·雷米",
	"actors": "托比·马奎尔 / 威廉·达福 / 克斯汀·邓斯特",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2002",
	"ticket": "$821.7 百万"
}, {
	"title": "独立日 Independence Day",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453518655.jpg",
	"score": "8.0",
	"scoreNum": "158248人评价",
	"director": " 罗兰·艾默里奇",
	"actors": "威尔·史密斯 / 比尔·普尔曼 / 杰夫·高布伦",
	"type": "动作 / 科幻 / 冒险 / 灾难",
	"country": "美国",
	"date": "1996",
	"ticket": "$817.4 百万"
}, {
	"title": "神奇动物在哪里 Fantastic Beasts and Where to Find Them",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2392444121.jpg",
	"score": "7.8",
	"scoreNum": "349033人评价",
	"director": " 大卫·叶茨",
	"actors": "埃迪·雷德梅恩 / 凯瑟琳·沃特斯顿 / 丹·福勒",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2016",
	"ticket": "$814.0 百万"
}, {
	"title": "寻梦环游记 Coco",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2503997609.jpg",
	"score": "9.0",
	"scoreNum": "609266人评价",
	"director": " 李·昂克里奇 / 阿德里安·莫利纳",
	"actors": "安东尼·冈萨雷斯 / 盖尔·加西亚·贝纳尔 / 本杰明·布拉特",
	"type": "喜剧 / 动画 / 奇幻 / 音乐",
	"country": "美国",
	"date": "2017",
	"ticket": "$807.1 百万"
}, {
	"title": "怪物史瑞克3 Shrek the Third",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p577871352.jpg",
	"score": "7.2",
	"scoreNum": "49816人评价",
	"director": " 克里斯·米勒 / 许诚毅",
	"actors": "麦克·梅尔斯 / 艾迪·墨菲 / 卡梅隆·迪亚兹",
	"type": "动画 / 冒险 / 喜剧 / 家庭 / 奇幻",
	"country": "美国",
	"date": "2007",
	"ticket": "$799.0 百万"
}, {
	"title": "哈利·波特与阿兹卡班的囚徒 Harry Potter and the Prisoner of Azkaban",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1910812549.jpg",
	"score": "8.3",
	"scoreNum": "214698人评价",
	"director": " 阿方索·卡隆",
	"actors": "丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2004",
	"ticket": "$796.7 百万"
}, {
	"title": "加勒比海盗5：死无对证 Pirates of the Caribbean: Dead Men Tell No Tales",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2459723975.jpg",
	"score": "7.2",
	"scoreNum": "220771人评价",
	"director": " 艾斯彭·山德伯格 / 乔阿吉姆·罗恩尼",
	"actors": "约翰尼·德普 / 哈维尔·巴登 / 杰弗里·拉什",
	"type": "动作 / 奇幻 / 冒险",
	"country": "美国",
	"date": "2017",
	"ticket": "$794.9 百万"
}, {
	"title": "E.T. 外星人 E.T.: The Extra-Terrestrial",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p984732992.jpg",
	"score": "8.5",
	"scoreNum": "180599人评价",
	"director": " 史蒂文·斯皮尔伯格",
	"actors": "亨利·托马斯 / 迪·沃伦斯 / 罗伯特·麦克纳夫顿",
	"type": "剧情 / 科幻",
	"country": "美国",
	"date": "1982",
	"ticket": "$792.9 百万"
}, {
	"title": "碟中谍6：全面瓦解 Mission: Impossible - Fallout",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2529365085.jpg",
	"score": "8.2",
	"scoreNum": "278905人评价",
	"director": " 克里斯托弗·麦奎里",
	"actors": "汤姆·克鲁斯 / 亨利·卡维尔 / 文·瑞姆斯",
	"type": "动作 / 惊悚 / 冒险",
	"country": "美国",
	"date": "2018",
	"ticket": "$791.0 百万"
}, {
	"title": "速度与激情6 Furious 6",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2024579845.jpg",
	"score": "7.7",
	"scoreNum": "173970人评价",
	"director": " 林诣彬",
	"actors": "范·迪塞尔 / 保罗·沃克 / 道恩·强森",
	"type": "动作 / 犯罪 / 惊悚",
	"country": "美国",
	"date": "2013",
	"ticket": "$788.7 百万"
}, {
	"title": "夺宝奇兵4 Indiana Jones and the Kingdom of the Crystal Skull",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1703349212.jpg",
	"score": "7.0",
	"scoreNum": "35373人评价",
	"director": " 史蒂文·斯皮尔伯格",
	"actors": "哈里森·福特 / 希亚·拉博夫 / 凯特·布兰切特",
	"type": "动作 / 冒险 / 惊悚",
	"country": "美国",
	"date": "2008",
	"ticket": "$786.6 百万"
}, {
	"title": "蜘蛛侠2 Spider-Man 2",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1617867110.jpg",
	"score": "7.3",
	"scoreNum": "138963人评价",
	"director": " 山姆·雷米",
	"actors": "托比·马奎尔 / 克斯汀·邓斯特 / 詹姆斯·弗兰科",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2004",
	"ticket": "$783.8 百万"
}, {
	"title": "死侍 Deadpool",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2309264172.jpg",
	"score": "7.6",
	"scoreNum": "232278人评价",
	"director": " 蒂姆·米勒",
	"actors": "瑞恩·雷诺兹 / 莫蕾娜·巴卡林 / 艾德·斯克林",
	"type": "喜剧 / 动作 / 科幻 / 冒险",
	"country": "美国/加拿大",
	"date": "2016",
	"ticket": "$783.1 百万"
}, {
	"title": "星球大战 Star Wars",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p732941361.jpg",
	"score": "8.3",
	"scoreNum": "74826人评价",
	"director": " 乔治·卢卡斯",
	"actors": "哈里森·福特 / 马克·哈米尔 / 凯丽·费雪",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "1977",
	"ticket": "$775.4 百万"
}, {
	"title": "银河护卫队 Guardians of the Galaxy",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2198455702.jpg",
	"score": "8.0",
	"scoreNum": "308928人评价",
	"director": " 詹姆斯·古恩",
	"actors": "克里斯·帕拉特 / 佐伊·索尔达娜 / 布莱德利·库珀",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国/英国",
	"date": "2014",
	"ticket": "$773.3 百万"
}, {
	"title": "2012",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p505238859.jpg",
	"score": "7.8",
	"scoreNum": "331608人评价",
	"director": " 罗兰·艾默里奇",
	"actors": "约翰·库萨克 / 切瓦特·埃加福特 / 阿曼达·皮特",
	"type": "动作 / 科幻 / 冒险 / 灾难",
	"country": "美国/加拿大",
	"date": "2009",
	"ticket": "$769.7 百万"
}, {
	"title": "沉睡魔咒 Maleficent",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2185343341.jpg",
	"score": "6.9",
	"scoreNum": "132062人评价",
	"director": " 罗伯特·斯特罗姆伯格",
	"actors": "安吉丽娜·朱莉 / 艾丽·范宁 / 沙尔托·科普雷",
	"type": "动作 / 爱情 / 奇幻 / 冒险",
	"country": "美国/英国",
	"date": "2014",
	"ticket": "$758.5 百万"
}, {
	"title": "达·芬奇密码 The Da Vinci Code",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453938764.jpg",
	"score": "7.2",
	"scoreNum": "160586人评价",
	"director": " 朗·霍华德",
	"actors": "汤姆·汉克斯 / 奥黛丽·塔图 / 伊恩·麦克莱恩",
	"type": "悬疑 / 惊悚",
	"country": "美国/马耳他/法国/英国",
	"date": "2006",
	"ticket": "$758.2 百万"
}, {
	"title": "超凡蜘蛛侠 The Amazing Spider-Man",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1527315971.jpg",
	"score": "7.3",
	"scoreNum": "176290人评价",
	"director": " 马克·韦布",
	"actors": "安德鲁·加菲尔德 / 艾玛·斯通 / 瑞斯·伊凡斯",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2012",
	"ticket": "$757.9 百万"
}, {
	"title": "饥饿游戏3：嘲笑鸟(上) The Hunger Games: Mockingjay - Part 1",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2222078042.jpg",
	"score": "5.9",
	"scoreNum": "102167人评价",
	"director": " 弗朗西斯·劳伦斯",
	"actors": "詹妮弗·劳伦斯 / 乔什·哈切森 / 利亚姆·海姆斯沃斯",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2014",
	"ticket": "$755.4 百万"
}, {
	"title": "怪物史瑞克4 Shrek Forever After",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p561405830.jpg",
	"score": "7.5",
	"scoreNum": "46090人评价",
	"director": " 迈克·米切尔",
	"actors": "麦克·梅尔斯 / 艾迪·墨菲 / 卡梅隆·迪亚兹",
	"type": "喜剧 / 动作 / 动画 / 冒险",
	"country": "美国",
	"date": "2010",
	"ticket": "$752.6 百万"
}, {
	"title": "X战警：逆转未来 X-Men: Days of Future Past",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2181156848.jpg",
	"score": "8.2",
	"scoreNum": "295375人评价",
	"director": " 布莱恩·辛格",
	"actors": "休·杰克曼 / 詹姆斯·麦卡沃伊 / 迈克尔·法斯宾德",
	"type": "动作 / 科幻 / 冒险",
	"country": "美国/英国",
	"date": "2014",
	"ticket": "$747.9 百万"
}, {
	"title": "马达加斯加3 Madagascar 3: Europe's Most Wanted",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1503869385.jpg",
	"score": "8.2",
	"scoreNum": "127108人评价",
	"director": " 康拉德·弗农 / 埃里克·达尼尔 / 汤姆·麦格拉思",
	"actors": "本·斯蒂勒 / 克里斯·洛克 / 大卫·休默",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2012",
	"ticket": "$746.9 百万"
}, {
	"title": "自杀小队 Suicide Squad",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2363084076.jpg",
	"score": "6.3",
	"scoreNum": "133062人评价",
	"director": " 大卫·阿耶",
	"actors": "威尔·史密斯 / 杰瑞德·莱托 / 玛格特·罗比",
	"type": "动作 / 犯罪 / 奇幻",
	"country": "美国",
	"date": "2016",
	"ticket": "$746.8 百万"
}, {
	"title": "纳尼亚传奇1：狮子、女巫和魔衣橱 The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p815647942.jpg",
	"score": "7.3",
	"scoreNum": "118902人评价",
	"director": " 安德鲁·亚当森",
	"actors": "乔芝·韩莉 / 斯堪德·凯恩斯 / 威廉·莫斯里",
	"type": "剧情 / 奇幻 / 冒险",
	"country": "英国/美国",
	"date": "2005",
	"ticket": "$745.0 百万"
}, {
	"title": "怪兽大学 Monsters University",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2033476722.jpg",
	"score": "8.1",
	"scoreNum": "218060人评价",
	"director": " 丹·斯坎隆",
	"actors": "比利·克里斯托 / 约翰·古德曼 / 史蒂夫·布西密",
	"type": "喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2013",
	"ticket": "$744.2 百万"
}, {
	"title": "黑客帝国2：重装上阵 The Matrix Reloaded",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p459054512.jpg",
	"score": "8.4",
	"scoreNum": "166396人评价",
	"director": " 莉莉·沃卓斯基 / 拉娜·沃卓斯基",
	"actors": "基努·里维斯 / 凯瑞-安·莫斯 / 劳伦斯·菲什伯恩",
	"type": "动作 / 科幻",
	"country": "美国/澳大利亚",
	"date": "2003",
	"ticket": "$742.1 百万"
}, {
	"title": "飞屋环游记 Up",
	"pic": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2364094053.jpg",
	"score": "8.9",
	"scoreNum": "642013人评价",
	"director": " 彼特·道格特 / 鲍勃·彼德森",
	"actors": "爱德华·阿斯纳 / 克里斯托弗·普卢默 / 乔丹·长井",
	"type": "剧情 / 喜剧 / 动画 / 冒险",
	"country": "美国",
	"date": "2009",
	"ticket": "$735.1 百万"
}, {
	"title": "死侍2 Deadpool 2",
	"pic": "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2521499639.jpg",
	"score": "7.5",
	"scoreNum": "136097人评价",
	"director": " 大卫·雷奇",
	"actors": "瑞恩·雷诺兹 / 乔什·布洛林 / 莫蕾娜·巴卡林",
	"type": "喜剧 / 动作 / 科幻 / 冒险",
	"country": "美国",
	"date": "2018",
	"ticket": "$734.2 百万"
}]